.TH "coda::db::named_param" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::named_param
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "\fBsql_value\fP \fBvalue\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "std::string coda::db::named_param::name"

.SS "\fBsql_value\fP coda::db::named_param::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
