.TH "coda::db::union_operator" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::union_operator
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <select_query\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunion_operator\fP (const \fBselect_query\fP &\fBquery\fP, union_op::type type=union_op::none)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBselect_query\fP \fBquery\fP"
.br
.ti -1c
.RI "union_op::type \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
union's one select query with another 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "coda::db::union_operator::union_operator (const \fBselect_query\fP & query, union_op::type type = \fCunion_op::none\fP)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIquery\fP the query to find 
.br
\fItype\fP the type of union 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
