.TH "coda::db::whereable< T >" 3 "Mon Apr 23 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::whereable< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwhereable\fP (const \fBwhereable\fP &other)=default"
.br
.ti -1c
.RI "\fBwhereable\fP (\fBwhereable\fP &&other)=default"
.br
.ti -1c
.RI "\fBwhereable\fP & \fBoperator=\fP (const \fBwhereable\fP &other)=default"
.br
.ti -1c
.RI "\fBwhereable\fP & \fBoperator=\fP (\fBwhereable\fP &&other)=default"
.br
.ti -1c
.RI "virtual \fBwhere_builder\fP & \fBwhere\fP ()=0"
.br
.ti -1c
.RI "virtual \fBwhere_builder\fP & \fBwhere\fP (const \fBsql_operator\fP &value)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
