.TH "coda::db::bind_mapping" 3 "Sat Dec 1 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::bind_mapping
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcoda::db::bindable\fP\&.
.PP
Inherited by \fBcoda::db::mysql::binding\fP, and \fBcoda::db::postgres::binding\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbind_mapping\fP & \fBbind\fP (const std::string &name, const \fBsql_value\fP &value) override"
.br
.ti -1c
.RI "std::string \fBprepare\fP (const std::string &sql, size_t max_index)"
.br
.ti -1c
.RI "\fBbindable\fP & \fBbind\fP (size_t index, const \fBsql_value\fP &value) override=0"
.br
.ti -1c
.RI "bool \fBis_named\fP () const"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBbind_mapping\fP& coda::db::bind_mapping::bind (const std::string & name, const \fBsql_value\fP & value)\fC [override]\fP, \fC [virtual]\fP"
bind a named parameter 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP the name of the parameter 
.br
\fIvalue\fP the value to bind 
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to this instance 
.RE
.PP

.PP
Implements \fBcoda::db::bindable\fP\&.
.PP
Reimplemented in \fBcoda::db::mysql::binding\fP, and \fBcoda::db::postgres::binding\fP\&.
.SS "\fBbindable\fP& coda::db::bind_mapping::bind (size_t index, const \fBsql_value\fP & value)\fC [override]\fP, \fC [pure virtual]\fP"
Binds a \fBsql_value\fP using the other bind methods 
.PP
\fBParameters:\fP
.RS 4
\fIindex\fP the index of the binding 
.br
\fIvalue\fP the value of the binding 
.RE
.PP
\fBReturns:\fP
.RS 4
a reference to this instance 
.RE
.PP

.PP
Implements \fBcoda::db::bindable\fP\&.
.PP
Implemented in \fBcoda::db::mysql::binding\fP, and \fBcoda::db::postgres::binding\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
