.TH "coda::db::sqlite::factory" 3 "Mon Apr 23 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::sqlite::factory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcoda::db::session_factory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::shared_ptr< \fBcoda::db::session_impl\fP > \fBcreate\fP (const \fBuri\fP &\fBuri\fP)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
