.TH "coda::db::helper::value_equality" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::helper::value_equality
.SH SYNOPSIS
.br
.PP
.PP
Inherits static_visitor< bool >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalue_equality\fP (const \fBsql_value\fP &value)"
.br
.ti -1c
.RI "template<typename V > bool \fBoperator()\fP (const V &value) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
