.TH "coda::db::mysql::column" 3 "Mon Apr 23 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::mysql::column
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <column\&.h>\fP
.PP
Inherits \fBcoda::db::column_impl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcolumn\fP (const std::shared_ptr< MYSQL_RES > &res, MYSQL_ROW value, size_t index)"
.br
.ti -1c
.RI "\fBcolumn\fP (const \fBcolumn\fP &other)=delete"
.br
.ti -1c
.RI "\fBcolumn\fP (\fBcolumn\fP &&other)"
.br
.ti -1c
.RI "\fBcolumn\fP & \fBoperator=\fP (const \fBcolumn\fP &other)=delete"
.br
.ti -1c
.RI "\fBcolumn\fP & \fBoperator=\fP (\fBcolumn\fP &&other)"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const"
.br
.ti -1c
.RI "\fBsql_value\fP \fBto_value\fP () const"
.br
.ti -1c
.RI "int \fBsql_type\fP () const"
.br
.ti -1c
.RI "std::string \fBname\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
a mysql specific implementation of a column using fetching 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "coda::db::mysql::column::column (const std::shared_ptr< MYSQL_RES > & res, MYSQL_ROW value, size_t index)"

.PP
\fBParameters:\fP
.RS 4
\fIres\fP the result for column meta data 
.br
\fIvalue\fP the column values for the result 
.br
\fIindex\fP the index of the column value 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool coda::db::mysql::column::is_valid () const\fC [virtual]\fP"
tests if this colums data validity 
.PP
\fBReturns:\fP
.RS 4
true if this columns data is valid 
.RE
.PP

.PP
Implements \fBcoda::db::column_impl\fP\&.
.SS "std::string coda::db::mysql::column::name () const\fC [virtual]\fP"

.PP
\fBReturns:\fP
.RS 4
the name of this column; 
.RE
.PP

.PP
Implements \fBcoda::db::column_impl\fP\&.
.SS "\fBsql_value\fP coda::db::mysql::column::to_value () const\fC [virtual]\fP"
converts this column to a value 
.PP
\fBReturns:\fP
.RS 4
the value of this column 
.RE
.PP

.PP
Implements \fBcoda::db::column_impl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
