.TH "coda::db::mysql::helper::res_delete" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::mysql::helper::res_delete
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resultset\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (MYSQL_RES *p) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
helper to clean up after a query result 

.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
