.TH "coda::db::mysql::stmt_resultset" 3 "Mon Apr 23 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::mysql::stmt_resultset
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resultset\&.h>\fP
.PP
Inherits \fBcoda::db::resultset_impl\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstmt_resultset\fP (const std::shared_ptr< \fBmysql::session\fP > &sess, const std::shared_ptr< MYSQL_STMT > &stmt)"
.br
.ti -1c
.RI "\fBstmt_resultset\fP (const \fBstmt_resultset\fP &other)=delete"
.br
.ti -1c
.RI "\fBstmt_resultset\fP & \fBoperator=\fP (const \fBstmt_resultset\fP &other)=delete"
.br
.ti -1c
.RI "\fBstmt_resultset\fP (\fBstmt_resultset\fP &&other)"
.br
.ti -1c
.RI "\fBstmt_resultset\fP & \fBoperator=\fP (\fBstmt_resultset\fP &&other)"
.br
.ti -1c
.RI "bool \fBis_valid\fP () const noexcept"
.br
.ti -1c
.RI "\fBstmt_resultset::row_type\fP \fBcurrent_row\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "bool \fBnext\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename , typename > class \fBresultset_iterator\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
a mysql specific implementation of a result set using prepared statements 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "coda::db::mysql::stmt_resultset::stmt_resultset (const std::shared_ptr< \fBmysql::session\fP > & sess, const std::shared_ptr< MYSQL_STMT > & stmt)"

.PP
\fBParameters:\fP
.RS 4
\fIdb\fP the database in use 
.br
\fIstmt\fP the statement being executed 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBstmt_resultset::row_type\fP coda::db::mysql::stmt_resultset::current_row ()\fC [virtual]\fP"
gets the current row in the results 
.PP
\fBReturns:\fP
.RS 4
the current row object 
.RE
.PP

.PP
Implements \fBcoda::db::resultset_impl\fP\&.
.SS "bool coda::db::mysql::stmt_resultset::is_valid () const\fC [virtual]\fP, \fC [noexcept]\fP"
tests if this implementation is valid 
.PP
\fBReturns:\fP
.RS 4
true if operations can be performed safely 
.RE
.PP

.PP
Implements \fBcoda::db::resultset_impl\fP\&.
.SS "bool coda::db::mysql::stmt_resultset::next ()\fC [virtual]\fP"
moves to the next row in the results 
.PP
\fBReturns:\fP
.RS 4
true if successful 
.RE
.PP

.PP
Implements \fBcoda::db::resultset_impl\fP\&.
.SS "void coda::db::mysql::stmt_resultset::reset ()\fC [virtual]\fP"
resets this resultset back to the first row 
.PP
Implements \fBcoda::db::resultset_impl\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
