.TH "coda::db::is_sql_string< T >" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::is_sql_string< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits integral_constant< bool, std::is_same< T, sql_string >::value||std::is_same< T, sql_wstring >::value >\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
