.TH "coda::db::column_definition" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::column_definition
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fBname\fP"
.br
.ti -1c
.RI "bool \fBpk\fP"
.br
.ti -1c
.RI "bool \fBautoincrement\fP"
.br
.ti -1c
.RI "std::string \fBtype\fP"
.br
.ti -1c
.RI "std::string \fBdefault_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition of a column in a schema 
.SH "Field Documentation"
.PP 
.SS "bool coda::db::column_definition::autoincrement"

.SS "std::string coda::db::column_definition::default_value"

.SS "std::string coda::db::column_definition::name"

.SS "bool coda::db::column_definition::pk"

.SS "std::string coda::db::column_definition::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
