.TH "coda::db::transaction::isolation" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::transaction::isolation
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBlevel\fP { \fBnone\fP, \fBserializable\fP, \fBrepeatable_read\fP, \fBread_commited\fP, \fBread_uncommited\fP }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
