.TH "coda::db::sqlite::helper::stmt_delete" 3 "Mon Apr 23 2018" "coda_db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::sqlite::helper::stmt_delete
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statement\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (sqlite3_stmt *p) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
helper to cleanup a sqlite3 statement 

.SH "Author"
.PP 
Generated automatically by Doxygen for coda_db from the source code\&.
