.TH "coda::db::sql_generator" 3 "Sat Dec 1 2018" "coda db" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coda::db::sql_generator
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBcoda::db::join_clause\fP, \fBcoda::db::query\fP, and \fBcoda::db::where_clause\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBto_sql\fP () const"
.br
.ti -1c
.RI "std::string \fBto_sql\fP ()"
.br
.ti -1c
.RI "virtual void \fBreset\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBgenerate_sql\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for coda db from the source code\&.
